### PR TITLE
Add Legit commit log pages

### PR DESCRIPTION
**Pull request by jfaz1**
This PR:
- Gets rid of the hardcoded 200 commit logs, instead gets them as needed per page to fill up the screen
- Adds forward/backward page binds to view the commit logs (f/b)

Notes:
- Could only test Git and Mercurial
- I'm very much a lisp noob so double check my logic; I used `lem/peek-legit:collector-buffer` to store the offset in order to avoid having a global `commits-offset` defvar/defparameter. That might be more idiomatic, I don't really know.
- You might want to clean up a bit (e.g. maybe we should remove `nb-commits-log`)

### CODE REVIEW

**Comment by vindarel** [comment]
yay :rocket: 

A question on usage: because of the pagination, we can't see and scroll (or search, etc) over a big list of commits from 0 to 100 or 200 or more. Is that the usage we want, or will we try to do better later? (this pagination is already better than nothing, of course) Pressing "b" and "f" each time runs a git command. That won't be an issue?

b and f need to be on a new keymap but I can do this later.

I'm OK to merge and iterate, but let's discuss a bit.

**Comment by jfaz1** [comment]
Yeah that's a good point; the way I implemented it here doesn't let us look ahead. Your original version is more seamless, because since it's a normal buffer you can just search for things offscreen. I was thinking mostly of the general view and not searchability here. If we were to add searchability to this method, we'd need a context switch, which is not as clean.

That being said, I don't know exactly what the right way to scale this would be. Lem doesn't seem to be able to handle large buffers as well as something like Emacs. Out of curiosity I tried seeing what would happen if I ran `git log --pretty=oneline > oneline.txt` in various repos. In many cases, it worked fine. Running it on the Linux repo yields a 122mb log, which crashed lem for me. On some smaller-yet-still-large logs (~30mb), lem loads it after a while, but it feels sluggish to use. Emacs, while being a bit sluggish, was still noticeably better at handling these.

This experience makes me think that if we go with your original method and try to avoid the context switch, we'd have to figure out how to improve Lem's large buffer handling, and then throw a background thread to fetch the log over time so we don't lag when opening the list for large repos like the Linux kernel. An alternative is to use pagination like in this PR, keeping only the relevant logs in scope, and then have dedicated search functionality using something like `git grep` (which would be a good bit faster than isearch on a larger repo/log buffer).

What are your thoughts? I was going to play around a bit more but seeing there's a competing PR I'll wait until that gets sorted out. I'll also ping @cxxxr in here in case he has any thoughts.

**Comment by vindarel** [comment]
mmh… best of both worlds: we keep your pagination, we add a bigger default offset: not only the window height, but 200, as a configurable parameter. Thoughts?

> git grep

+1, will be nice.

**Comment by jfaz1** [comment]
Yeah that actually sounds like a pretty good interim solution!

**Comment by vindarel** [comment]
great. Looking forward for your commits.

other idea: add "F" and "B" to go the last and first page of the commits history. Like real pagination buttons.

**Comment by jfaz1** [comment]
Alright, went ahead and changed it so it has the same pagination, but with the configurable offset. Also threw in the first/last page commands. 

Note: The last page one works fine on my PC on most repos, but the really large ones like the Linux kernel one take pretty long. We should try figuring out a way of optimizing that at some point. I tried with commands like `rev-list` in the shell and it still took too long.

**Comment by jfaz1** [comment]
Added a dedicated command to count commits anyways, seems to work fine on Mercurial as well. Switched to `rev-list` since it still offered some decent performance improvements over `log`.

**Comment by vindarel** [comment]
Excellent additions thanks. Lem and lem/legit are in good shape and have *many* contributors, exciting times :)

**Comment by vindarel** [comment]
yeah the count with git rev-parse is a bit slow. It's fast on Lem's repository. (It seems to work better when git is "warmed up"?)

**Comment by jfaz1** [comment]
> yeah the count with git rev-parse is a bit slow. It's fast on Lem's repository. (It seems to work better when git is "warmed up"?)

Yeah I played around but couldn't come up with a good solution besides maybe caching it or something.

**Pull request merged**
